### ISSUE TITLE
docker pull 跟 login 始终返回 401

### ISSUE THREAD

**Issue by liuweiGL** [ciiiii/cloudflare-docker-proxy#11]
路由配置：
```
const routes = {
  "docker.xx.tech": "https://registry-1.docker.io",
  "quay.xx.tech": "https://quay.io",
  "gcr.xx.tech": "https://gcr.io",
  "k8s-gcr.xx.tech": "https://k8s.gcr.io",
  "k8s.xx.tech": "https://registry.k8s.io",
  "ghcr.xx.tech": "https://ghcr.io",
  "cloudsmith.xx.tech": "https://docker.cloudsmith.io",
};
```
使用 docker pull docker.xx.tech/hello-world 返回 401，docker login 也是返回 401 无法登录

**Comment by ciiiii** [comment]
duplicates of https://github.com/ciiiii/cloudflare-docker-proxy/issues/5, but I can support it if required

**Comment by liuweiGL** [comment]
麻烦作者大大抽空完善下吧，现在的环境下这个项目的作用很大

**Comment by 1574242600** [comment]
要拉取官方镜像，可以加上 `library`
```
docker pull docker.xx.tech/library/hello-world
```

**Comment by ciiiii** [comment]
fixed by #14 and #15 , please have a try @liuweiGL

**Comment by ciiiii** [comment]
@1574242600 Please help create an issue, I'm considering how to support this special case.
