### ISSUE TITLE
bug fix

### ISSUE THREAD

**Issue by yuze66** [ciiiii/cloudflare-docker-proxy#29]
routes = [
  { pattern = "docker.libcuda.so", custom_domain = true },
  { pattern = "quey.libcuda.so", custom_domain = true },
  { pattern = "gcr.libcuda.so", custom_domain = true },
  { pattern = "k8s-gcr.libcuda.so", custom_domain = true },
  { pattern = "k8s.libcuda.so", custom_domain = true },
  { pattern = "ghcr.libcuda.so", custom_domain = true },
  { pattern = "cloudsmith.libcuda.so", custom_domain = true },
]
]

maybe is  quay? not quey

**Comment by ciiiii** [comment]
fixed by #23
