### ISSUE TITLE
部署错误

### ISSUE THREAD

**Issue by MaxKingPor** [ciiiii/cloudflare-docker-proxy#37]
![image](https://github.com/ciiiii/cloudflare-docker-proxy/assets/43533178/7127bd00-72ea-4df8-b638-58e368730bcc)
![image](https://github.com/ciiiii/cloudflare-docker-proxy/assets/43533178/0544d849-73a2-438a-843a-3a97a3ce3ba4)

**Comment by jerryzhang721** [comment]
the same issue

**Comment by MaxKingPor** [comment]
> the same issue

I didn't add any DNS records
![image](https://github.com/ciiiii/cloudflare-docker-proxy/assets/43533178/4052be08-8522-47d5-899a-46a0924f47b0)

**Comment by Cloudy-Kumori** [comment]
应该是需要fork到自己的github账户后对配置文件进行修改，使用readme.md文件下面的deploy with Workers按钮（https://deploy.workers.cloudflare.com/?url=https://github.com/{your username}/cloudflare-docker-proxy）来触发action的启动，自己运行wrangler可能会遇到问题

**Comment by yqchilde** [comment]
解决办法：修改wrangler.toml里的域名为自己的，和index.js里的对应
