### ISSUE TITLE
Deploy one docker hub proxy

### ISSUE THREAD

**Issue by yyu0378** [ciiiii/cloudflare-docker-proxy#41]
I try deploy one docker hub proxy,when pull image fail,show  need auth.So need more some config.
![12](https://github.com/ciiiii/cloudflare-docker-proxy/assets/2733175/71fe024d-01f7-44a1-a112-4f368639826c)

**Comment by ciiiii** [comment]
I can't reproduce the error, can you check the detail of your cloudflare worker status.
