### ISSUE TITLE
这个怎么使用呀？

### ISSUE THREAD

**Issue by jiamliang** [ciiiii/cloudflare-docker-proxy#8]
看了 README.md 文档，但是还是不知道怎么使用。

**Comment by xyzzen** [comment]
学会了没。。我也没看明白 现在使用  "gcr.xxx": "https://gcr.io" 发现不行的

**Comment by jiamliang** [comment]
https://github.com/jiamliang/cloudflare-docker-proxy/blob/master/README.md

**Comment by daiaji** [comment]
说起来为什么不用环境变量配置域名呢？
